### ISSUE TITLE
Help!!! Can not get message when i run meshblu on ubuntu14.04 x64

### ISSUE THREAD

**Issue by tryeasy** [octoblu/meshblu#127] opened 2016-04-04 15:22 UTC
1. Do not start redis : get a error
`Cannot call method 'in' of undefined TypeError: Cannot call method 'in' of undefined
  at /home/zhai/wwwroot/meshblu/lib/messageIOEmitter.coffee:16:7
  at arrayEach (/home/zhai/wwwroot/meshblu/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/home/zhai/wwwroot/meshblu/node_modules/lodash/index.js:3345:13)
`
2. Start redis : subscribe to a device and send message by http, but receive nothing.
the console log seems ok:
`{"name":"mosca","hostname":"ubuntu","pid":3386,"client":"26be93af-d1e8-4a02-909c-7ee87a95e847","level":30,"topic":"26be93af-d1e8-4a02-909c-7ee87a95e847_bc","qos":0,"msg":"subscribed to topic","time":"2016-04-04T11:12:22.170Z","v":0}
`
3. When i use the lastest docker image from octoblu, message cannot be received too.
`sudo docker run -p 8000:80 -p 1883:1883 -e TOKEN=8533f616a4c0282b942b0c0b435b8124a00127fb octoblu/meshblu`

**It works perfectly when i use a mac. But when switching to a ubuntu14.04, i am confuzed. This issue has traped me for at least 3 days. I need your help.**

**(The code that i use is 1.4.1.)**

**Comment by royvandewater** [comment] 2016-04-04 16:13
Commit cf405... should fix meshblu running without a Redis to connect to, which should address the third issue you described (running in docker). 

In the first issue you described, where you do not start Redis, I believe it's still trying to connect. You'll have to make sure that it doesn't try to connect by running it without a `REDIS_HOST` environment variable, or by setting the `REDIS_HOST` variable to the empty string.

I'm looking into the second issue (connecting to an external redis server) right now.

**Comment by royvandewater** [comment] 2016-04-04 16:28
I'm afraid I'm unable to reproduce your second issue. I'm going to close this for now, until we have some steps to reproduce it. Please let us know how to recreate what you're seeing, I'm happy to reopen the issue and address the problem :-)

**Closed by royvandewater** 2016-04-04 16:28 UTC
